# Загрузите в колаб файлы по оценкам (ratings) и фильмам (movies) и создайте на их основе pandas-датафреймы

In [ ]:
import pandas as pd

pandas-датафрейм movies

In [ ]:
m_cols = ['movie_id',
 'movie_title',
 'release_date',
 'video_release_date',
 'IMDb_URL',
 'unknown',
 'Action',
 'Adventure',
 'Animation',
 'Children',
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci_Fi',
 'Thriller',
 'War',
 'Western']

uitem = pd.read_csv('/content/u.item.csv', sep='|', names=m_cols , encoding='latin-1')

In [ ]:
uitem.describe()

,movie_id,video_release_date,unknown,Action,Adventure,Animation,Children,Comedy,Crime,Documentary,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci_Fi,Thriller,War,Western
count,1682.000000,0.0,1682.000000,1682.000000,1682.000000,1682.000000,1682.000000,1682.000000,1682.000000,1682.000000,...,1682.00000,1682.000000,1682.000000,1682.000000,1682.000000,1682.000000,1682.000000,1682.000000,1682.000000,1682.000000
mean,841.500000,NaN,0.001189,0.149227,0.080262,0.024970,0.072533,0.300238,0.064804,0.029727,...,0.01308,0.014269,0.054697,0.033294,0.036266,0.146849,0.060048,0.149227,0.042212,0.016052
std,485.695893,NaN,0.034473,0.356418,0.271779,0.156081,0.259445,0.458498,0.246253,0.169882,...,0.11365,0.118632,0.227455,0.179456,0.187008,0.354061,0.237646,0.356418,0.201131,0.125714
min,1.000000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,421.250000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,841.500000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1261.750000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1682.000000,NaN,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [ ]:
movies = uitem

In [ ]:
movies.columns

Index(['movie_id', 'movie_title', 'release_date', 'video_release_date',
       'IMDb_URL', 'unknown', 'Action', 'Adventure', 'Animation', 'Children',
       'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy', 'Film-Noir',
       'Horror', 'Musical', 'Mystery', 'Romance', 'Sci_Fi', 'Thriller', 'War',
       'Western'],
      dtype='object')

In [ ]:
movies.drop(['video_release_date', 'IMDb_URL'], axis=1, inplace=True)

movies

,movie_id,movie_title,release_date,unknown,Action,Adventure,Animation,Children,Comedy,Crime,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci_Fi,Thriller,War,Western
0,1,Toy Story (1995),01-Jan-1995,0,0,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),01-Jan-1995,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms (1995),01-Jan-1995,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,4,Get Shorty (1995),01-Jan-1995,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,5,Copycat (1995),01-Jan-1995,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1677,1678,Mat' i syn (1997),06-Feb-1998,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1678,1679,B. Monkey (1998),06-Feb-1998,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
1679,1680,Sliding Doors (1998),01-Jan-1998,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1680,1681,You So Crazy (1994),01-Jan-1994,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1681,1682,Scream of Stone (Schrei aus Stein) (1991),08-Mar-1996,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

pandas-датафрейм raitings

In [ ]:
udata = pd.read_csv('/content/u.data.csv', sep=';', header=0 , encoding='latin-1')

In [ ]:
udata.describe()

            user_id        item_id         rating     timestamp
count  100000.00000  100000.000000  100000.000000  1.000000e+05
mean      462.48475     425.530130       3.529860  8.835289e+08
std       266.61442     330.798356       1.125674  5.343856e+06
min         1.00000       1.000000       1.000000  8.747247e+08
25%       254.00000     175.000000       3.000000  8.794487e+08
50%       447.00000     322.000000       4.000000  8.828269e+08
75%       682.00000     631.000000       4.000000  8.882600e+08
max       943.00000    1682.000000       5.000000  8.932866e+08

In [ ]:
ratings = udata

In [ ]:
ratings.columns

Index(['user_id', 'item_id', 'rating', 'timestamp'], dtype='object')

In [ ]:
ratings.drop(['timestamp'], axis=1, inplace=True)

ratings

       user_id  item_id  rating
0          196      242       3
1          186      302       3
2           22      377       1
3          244       51       2
4          166      346       1
...        ...      ...     ...
99995      880      476       3
99996      716      204       5
99997      276     1090       1
99998       13      225       2
99999       12      203       3

[100000 rows x 3 columns]

# Средствами Pandas, используя dataframe ratings, найдите id пользователя, поставившего больше всего оценок

id пользователей сортированные по количеству оценок

In [ ]:
count_id = (ratings.groupby(['user_id']).agg('size'))
count_id.sort_values(ascending=False)

user_id
405    737
655    685
13     636
450    540
276    518
      ...
685     20
475     20
36      20
732     20
596     20
Length: 943, dtype: int64

In [ ]:
count_id.sort_values(ascending=False).head(1)

user_id
405    737
dtype: int64

In [ ]:
print('id пользователя, поставившего больше всего оценок  = ', *count_id.sort_values(ascending=False).head(1).index)

id пользователя, поставившего больше всего оценок  =  405

# Оставьте в датафрейме ratings только те фильмы, который оценил данный пользователь

In [ ]:
ratings[ratings['user_id']==405]

       user_id  item_id  rating
12276      405       56       4
12383      405      592       1
12430      405     1582       1
12449      405      171       1
12460      405      580       1
...        ...      ...     ...
98956      405      375       1
98978      405      445       4
99148      405     1246       1
99465      405      196       1
99756      405      958       1

[737 rows x 3 columns]

# Добавьте к датафрейму из задания 3 столбцы:
По жанрам. Каждый столбец - это жанр. Единицу записываем, если фильм принадлежит данному жанру и 0 - если нет
столбцы с общим количеством оценок от всех пользователей на фильм и суммарной оценкой от всех пользователей

In [ ]:
ratings.columns, movies.columns

(Index(['user_id', 'item_id', 'rating'], dtype='object'),
 Index(['movie_id', 'movie_title', 'release_date', 'unknown', 'Action',
        'Adventure', 'Animation', 'Children', 'Comedy', 'Crime', 'Documentary',
        'Drama', 'Fantasy', 'Film-Noir', 'Horror', 'Musical', 'Mystery',
        'Romance', 'Sci_Fi', 'Thriller', 'War', 'Western'],
       dtype='object'))

In [ ]:
ratings.rename(columns={'item_id': 'movie_id'}, inplace=True)

In [ ]:
rat_merged = pd.merge(ratings, movies)

In [ ]:
rat_merged.iloc[345]

user_id                              801
movie_id                             302
rating                                 4
movie_title     L.A. Confidential (1997)
release_date                 01-Jan-1997
unknown                                0
Action                                 0
Adventure                              0
Animation                              0
Children                               0
Comedy                                 0
Crime                                  1
Documentary                            0
Drama                                  0
Fantasy                                0
Film-Noir                              1
Horror                                 0
Musical                                0
Mystery                                1
Romance                                0
Sci_Fi                                 0
Thriller                               1
War                                    0
Western                                0
Name: 345, dtype: object

In [ ]:
rat_merged.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 100000 entries, 0 to 99999
Data columns (total 24 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   user_id       100000 non-null  int64
 1   movie_id      100000 non-null  int64
 2   rating        100000 non-null  int64
 3   movie_title   100000 non-null  object
 4   release_date  99991 non-null   object
 5   unknown       100000 non-null  int64
 6   Action        100000 non-null  int64
 7   Adventure     100000 non-null  int64
 8   Animation     100000 non-null  int64
 9   Children      100000 non-null  int64
 10  Comedy        100000 non-null  int64
 11  Crime         100000 non-null  int64
 12  Documentary   100000 non-null  int64
 13  Drama         100000 non-null  int64
 14  Fantasy       100000 non-null  int64
 15  Film-Noir     100000 non-null  int64
 16  Horror        100000 non-null  int64
 17  Musical       100000 non-null  int64
 18  Mystery       100000 non-null  int64
 19  Romance       100000 non-null  int64
 20  Sci_Fi        100000 non-null  int64
 21  Thriller      100000 non-null  int64
 22  War           100000 non-null  int64
 23  Western       100000 non-null  int64
dtypes: int64(22), object(2)
memory usage: 19.1+ MB

In [ ]:
rat_merged.dropna(axis=0, how='any', thresh=None, subset=None, inplace=True)
rat_merged.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 99991 entries, 0 to 99999
Data columns (total 24 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   user_id       99991 non-null  int64
 1   movie_id      99991 non-null  int64
 2   rating        99991 non-null  int64
 3   movie_title   99991 non-null  object
 4   release_date  99991 non-null  object
 5   unknown       99991 non-null  int64
 6   Action        99991 non-null  int64
 7   Adventure     99991 non-null  int64
 8   Animation     99991 non-null  int64
 9   Children      99991 non-null  int64
 10  Comedy        99991 non-null  int64
 11  Crime         99991 non-null  int64
 12  Documentary   99991 non-null  int64
 13  Drama         99991 non-null  int64
 14  Fantasy       99991 non-null  int64
 15  Film-Noir     99991 non-null  int64
 16  Horror        99991 non-null  int64
 17  Musical       99991 non-null  int64
 18  Mystery       99991 non-null  int64
 19  Romance       99991 non-null  int64
 20  Sci_Fi        99991 non-null  int64
 21  Thriller      99991 non-null  int64
 22  War           99991 non-null  int64
 23  Western       99991 non-null  int64
dtypes: int64(22), object(2)
memory usage: 19.1+ MB

In [ ]:
rat_merged['release_date'] = pd.to_datetime(rat_merged['release_date'])

rat_merged['release_date']

0       1997-01-24
1       1997-01-24
2       1997-01-24
3       1997-01-24
4       1997-01-24
           ...
99995   1962-01-01
99996   1996-11-01
99997   1996-08-23
99998   1996-02-02
99999   1996-09-18
Name: release_date, Length: 99991, dtype: datetime64[ns]

In [ ]:
rat_merged['release_date'] = rat_merged['release_date'].dt.year

rat_merged['release_date']

0        1997
1        1997
2        1997
3        1997
4        1997
         ...
99995    1962
99996    1996
99997    1996
99998    1996
99999    1996
Name: release_date, Length: 99991, dtype: int64

In [ ]:
rat_merged

,user_id,movie_id,rating,movie_title,release_date,unknown,Action,Adventure,Animation,Children,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci_Fi,Thriller,War,Western
0,196,242,3,Kolya (1996),1997,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,63,242,3,Kolya (1996),1997,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,226,242,5,Kolya (1996),1997,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,154,242,3,Kolya (1996),1997,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,306,242,5,Kolya (1996),1997,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,840,1674,4,Mamma Roma (1962),1962,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
99996,655,1640,3,"Eighth Day, The (1996)",1996,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
99997,655,1637,3,Girls Town (1996),1996,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
99998,655,1630,3,"Silence of the Palace, The (Saimt el Qusur) (1...",1996,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
99999,655,1641,3,Dadetown (1995),1996,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

# Сформируйте X_train, X_test, y_train, y_test

In [ ]:
df = rat_merged

In [ ]:
df.columns

Index(['user_id', 'movie_id', 'rating', 'movie_title', 'release_date',
       'unknown', 'Action', 'Adventure', 'Animation', 'Children', 'Comedy',
       'Crime', 'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horror',
       'Musical', 'Mystery', 'Romance', 'Sci_Fi', 'Thriller', 'War',
       'Western'],
      dtype='object')

In [ ]:
X, y = df[['user_id', 'movie_id', 'release_date',
       'unknown', 'Action', 'Adventure', 'Animation', 'Children', 'Comedy',
       'Crime', 'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horror',
       'Musical', 'Mystery', 'Romance', 'Sci_Fi', 'Thriller', 'War',
       'Western']], df['rating']

# Возьмите модель линейной регрессии (или любую другую для задачи регрессии)  и обучите ее на фильмах

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [ ]:
X_train.head()

,user_id,movie_id,release_date,unknown,Action,Adventure,Animation,Children,Comedy,Crime,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci_Fi,Thriller,War,Western
45526,363,176,1986,0,1,0,0,0,0,0,...,0,0,0,0,0,0,1,1,1,0
1451,405,86,1993,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35957,868,189,1992,0,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
28942,5,228,1982,0,1,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
92105,85,519,1948,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
model = LinearRegression()
model

LinearRegression()

In [ ]:
model.fit(X_train, y_train)

LinearRegression()

# Оцените качество модели на X_test, y_test при помощи метрик для задачи регрессии

In [ ]:
from sklearn.metrics import mean_squared_error

In [ ]:
mean_squared_error(y_train, model.predict(X_train)) # Оцениваем качество на выборке для обучения

1.1508062800221912

In [ ]:
mean_squared_error(y_test, model.predict(X_test))# Оцениваем качество на выборке для тестирования RSE

1.152873125501573

In [ ]:
mean_squared_error(y_test, model.predict(X_test), squared=False)# Оцениваем качество на выборке для тестирования RMSE

1.0737192954872203

In [ ]:
max(y)-min(y)

4

# Загрузить данные в spark

In [ ]:
!apt-get update

Get:1 https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/ InRelease [3,626 B]
Hit:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease
Get:3 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Hit:4 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:5 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu bionic InRelease [15.9 kB]
Ign:6 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Get:7 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Hit:8 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release
Hit:9 http://ppa.launchpad.net/cran/libgit2/ubuntu bionic InRelease
Get:10 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Hit:11 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu bionic InRelease
Hit:12 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu bionic InRelease
Get:14 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu bionic/main Sources [2,075 kB]
Get:15 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [2,871 kB]
Get:16 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [2,298 kB]
Get:17 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [1,031 kB]
Get:18 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1,521 kB]
Get:19 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu bionic/main amd64 Packages [1,063 kB]
Get:20 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [3,302 kB]
Get:21 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [1,075 kB]
Fetched 15.5 MB in 4s (4,130 kB/s)
Reading package lists... Done

In [ ]:
!apt-get install openjdk-8-jdk-headless -qq > /dev/null

In [ ]:
!wget -q https://downloads.apache.org/spark/spark-3.2.1/spark-3.2.1-bin-hadoop2.7.tgz

In [ ]:
!tar -xvf spark-3.2.1-bin-hadoop2.7.tgz

spark-3.2.1-bin-hadoop2.7/
spark-3.2.1-bin-hadoop2.7/LICENSE
spark-3.2.1-bin-hadoop2.7/NOTICE
spark-3.2.1-bin-hadoop2.7/R/
spark-3.2.1-bin-hadoop2.7/R/lib/
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/DESCRIPTION
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/INDEX
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/Meta/
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/Meta/Rd.rds
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/Meta/features.rds
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/Meta/hsearch.rds
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/Meta/links.rds
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/Meta/nsInfo.rds
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/Meta/package.rds
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/NAMESPACE
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/R/
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/R/SparkR
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/R/SparkR.rdb
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/R/SparkR.rdx
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/help/
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/help/AnIndex
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/help/SparkR.rdb
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/help/SparkR.rdx
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/help/aliases.rds
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/help/paths.rds
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/html/
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/html/00Index.html
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/html/R.css
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/profile/
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/profile/general.R
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/profile/shell.R
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/tests/
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/tests/testthat/
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/tests/testthat/test_basic.R
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/worker/
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/worker/daemon.R
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/worker/worker.R
spark-3.2.1-bin-hadoop2.7/R/lib/sparkr.zip
spark-3.2.1-bin-hadoop2.7/README.md
spark-3.2.1-bin-hadoop2.7/RELEASE
spark-3.2.1-bin-hadoop2.7/bin/
spark-3.2.1-bin-hadoop2.7/bin/beeline
spark-3.2.1-bin-hadoop2.7/bin/beeline.cmd
spark-3.2.1-bin-hadoop2.7/bin/docker-image-tool.sh
spark-3.2.1-bin-hadoop2.7/bin/find-spark-home
spark-3.2.1-bin-hadoop2.7/bin/find-spark-home.cmd
spark-3.2.1-bin-hadoop2.7/bin/load-spark-env.cmd
spark-3.2.1-bin-hadoop2.7/bin/load-spark-env.sh
spark-3.2.1-bin-hadoop2.7/bin/pyspark
spark-3.2.1-bin-hadoop2.7/bin/pyspark.cmd
spark-3.2.1-bin-hadoop2.7/bin/pyspark2.cmd
spark-3.2.1-bin-hadoop2.7/bin/run-example
spark-3.2.1-bin-hadoop2.7/bin/run-example.cmd
spark-3.2.1-bin-hadoop2.7/bin/spark-class
spark-3.2.1-bin-hadoop2.7/bin/spark-class.cmd
spark-3.2.1-bin-hadoop2.7/bin/spark-class2.cmd
spark-3.2.1-bin-hadoop2.7/bin/spark-shell
spark-3.2.1-bin-hadoop2.7/bin/spark-shell.cmd
spark-3.2.1-bin-hadoop2.7/bin/spark-shell2.cmd
spark-3.2.1-bin-hadoop2.7/bin/spark-sql
spark-3.2.1-bin-hadoop2.7/bin/spark-sql.cmd
spark-3.2.1-bin-hadoop2.7/bin/spark-sql2.cmd
spark-3.2.1-bin-hadoop2.7/bin/spark-submit
spark-3.2.1-bin-hadoop2.7/bin/spark-submit.cmd
spark-3.2.1-bin-hadoop2.7/bin/spark-submit2.cmd
spark-3.2.1-bin-hadoop2.7/bin/sparkR
spark-3.2.1-bin-hadoop2.7/bin/sparkR.cmd
spark-3.2.1-bin-hadoop2.7/bin/sparkR2.cmd
spark-3.2.1-bin-hadoop2.7/conf/
spark-3.2.1-bin-hadoop2.7/conf/fairscheduler.xml.template
spark-3.2.1-bin-hadoop2.7/conf/log4j.properties.template
spark-3.2.1-bin-hadoop2.7/conf/metrics.properties.template
spark-3.2.1-bin-hadoop2.7/conf/spark-defaults.conf.template
spark-3.2.1-bin-hadoop2.7/conf/spark-env.sh.template
spark-3.2.1-bin-hadoop2.7/conf/workers.template
spark-3.2.1-bin-hadoop2.7/data/
spark-3.2.1-bin-hadoop2.7/data/graphx/
spark-3.2.1-bin-hadoop2.7/data/graphx/followers.txt
spark-3.2.1-bin-hadoop2.7/data/graphx/users.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/
spark-3.2.1-bin-hadoop2.7/data/mllib/als/
spark-3.2.1-bin-hadoop2.7/data/mllib/als/sample_movielens_ratings.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/als/test.data
spark-3.2.1-bin-hadoop2.7/data/mllib/gmm_data.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/images/
spark-3.2.1-bin-hadoop2.7/data/mllib/images/license.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/images/origin/
spark-3.2.1-bin-hadoop2.7/data/mllib/images/origin/kittens/
spark-3.2.1-bin-hadoop2.7/data/mllib/images/origin/kittens/29.5.a_b_EGDP022204.jpg
spark-3.2.1-bin-hadoop2.7/data/mllib/images/origin/kittens/54893.jpg
spark-3.2.1-bin-hadoop2.7/data/mllib/images/origin/kittens/DP153539.jpg
spark-3.2.1-bin-hadoop2.7/data/mllib/images/origin/kittens/DP802813.jpg
spark-3.2.1-bin-hadoop2.7/data/mllib/images/origin/kittens/not-image.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/images/origin/license.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/images/origin/multi-channel/
spark-3.2.1-bin-hadoop2.7/data/mllib/images/origin/multi-channel/BGRA.png
spark-3.2.1-bin-hadoop2.7/data/mllib/images/origin/multi-channel/BGRA_alpha_60.png
spark-3.2.1-bin-hadoop2.7/data/mllib/images/origin/multi-channel/chr30.4.184.jpg
spark-3.2.1-bin-hadoop2.7/data/mllib/images/origin/multi-channel/grayscale.jpg
spark-3.2.1-bin-hadoop2.7/data/mllib/images/partitioned/
spark-3.2.1-bin-hadoop2.7/data/mllib/images/partitioned/cls=kittens/
spark-3.2.1-bin-hadoop2.7/data/mllib/images/partitioned/cls=kittens/date=2018-01/
spark-3.2.1-bin-hadoop2.7/data/mllib/images/partitioned/cls=kittens/date=2018-01/29.5.a_b_EGDP022204.jpg
spark-3.2.1-bin-hadoop2.7/data/mllib/images/partitioned/cls=kittens/date=2018-01/not-image.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/images/partitioned/cls=kittens/date=2018-02/
spark-3.2.1-bin-hadoop2.7/data/mllib/images/partitioned/cls=kittens/date=2018-02/54893.jpg
spark-3.2.1-bin-hadoop2.7/data/mllib/images/partitioned/cls=kittens/date=2018-02/DP153539.jpg
spark-3.2.1-bin-hadoop2.7/data/mllib/images/partitioned/cls=kittens/date=2018-02/DP802813.jpg
spark-3.2.1-bin-hadoop2.7/data/mllib/images/partitioned/cls=multichannel/
spark-3.2.1-bin-hadoop2.7/data/mllib/images/partitioned/cls=multichannel/date=2018-01/
spark-3.2.1-bin-hadoop2.7/data/mllib/images/partitioned/cls=multichannel/date=2018-01/BGRA.png
spark-3.2.1-bin-hadoop2.7/data/mllib/images/partitioned/cls=multichannel/date=2018-01/BGRA_alpha_60.png
spark-3.2.1-bin-hadoop2.7/data/mllib/images/partitioned/cls=multichannel/date=2018-02/
spark-3.2.1-bin-hadoop2.7/data/mllib/images/partitioned/cls=multichannel/date=2018-02/chr30.4.184.jpg
spark-3.2.1-bin-hadoop2.7/data/mllib/images/partitioned/cls=multichannel/date=2018-02/grayscale.jpg
spark-3.2.1-bin-hadoop2.7/data/mllib/iris_libsvm.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/kmeans_data.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/pagerank_data.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/pic_data.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/ridge-data/
spark-3.2.1-bin-hadoop2.7/data/mllib/ridge-data/lpsa.data
spark-3.2.1-bin-hadoop2.7/data/mllib/sample_binary_classification_data.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/sample_fpgrowth.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/sample_isotonic_regression_libsvm_data.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/sample_kmeans_data.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/sample_lda_data.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/sample_lda_libsvm_data.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/sample_libsvm_data.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/sample_linear_regression_data.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/sample_movielens_data.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/sample_multiclass_classification_data.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/sample_svm_data.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/streaming_kmeans_data_test.txt
spark-3.2.1-bin-hadoop2.7/data/streaming/
spark-3.2.1-bin-hadoop2.7/data/streaming/AFINN-111.txt
spark-3.2.1-bin-hadoop2.7/examples/
spark-3.2.1-bin-hadoop2.7/examples/jars/
spark-3.2.1-bin-hadoop2.7/examples/jars/scopt_2.12-3.7.1.jar
spark-3.2.1-bin-hadoop2.7/examples/jars/spark-examples_2.12-3.2.1.jar
spark-3.2.1-bin-hadoop2.7/examples/src/
spark-3.2.1-bin-hadoop2.7/examples/src/main/
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/JavaHdfsLR.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/JavaLogQuery.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/JavaPageRank.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/JavaSparkPi.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/JavaStatusTrackerDemo.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/JavaTC.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/JavaWordCount.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaAFTSurvivalRegressionExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaALSExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaBinarizerExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaBisectingKMeansExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaBucketedRandomProjectionLSHExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaBucketizerExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaChiSqSelectorExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaChiSquareTestExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaCorrelationExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaCountVectorizerExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaDCTExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaDecisionTreeClassificationExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaDecisionTreeRegressionExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaDocument.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaElementwiseProductExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaEstimatorTransformerParamExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaFMClassifierExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaFMRegressorExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaFPGrowthExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaFeatureHasherExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaGaussianMixtureExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaGeneralizedLinearRegressionExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaGradientBoostedTreeClassifierExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaGradientBoostedTreeRegressorExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaImputerExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaIndexToStringExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaInteractionExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaIsotonicRegressionExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaKMeansExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaLDAExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaLabeledDocument.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaLinearRegressionWithElasticNetExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaLinearSVCExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaLogisticRegressionSummaryExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaLogisticRegressionWithElasticNetExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaMaxAbsScalerExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaMinHashLSHExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaMinMaxScalerExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaModelSelectionViaCrossValidationExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaModelSelectionViaTrainValidationSplitExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaMulticlassLogisticRegressionWithElasticNetExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaMultilayerPerceptronClassifierExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaNGramExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaNaiveBayesExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaNormalizerExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaOneHotEncoderExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaOneVsRestExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaPCAExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaPipelineExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaPolynomialExpansionExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaPowerIterationClusteringExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaPrefixSpanExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaQuantileDiscretizerExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaRFormulaExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaRandomForestClassifierExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaRandomForestRegressorExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaRobustScalerExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaSQLTransformerExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaStandardScalerExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaStopWordsRemoverExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaStringIndexerExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaSummarizerExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaTfIdfExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaTokenizerExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaUnivariateFeatureSelectorExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaVarianceThresholdSelectorExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaVectorAssemblerExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaVectorIndexerExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaVectorSizeHintExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaVectorSlicerExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaWord2VecExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaALS.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaAssociationRulesExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaBinaryClassificationMetricsExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaBisectingKMeansExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaChiSqSelectorExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaCorrelationsExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaDecisionTreeClassificationExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaDecisionTreeRegressionExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaElementwiseProductExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaGaussianMixtureExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaGradientBoostingClassificationExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaGradientBoostingRegressionExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaHypothesisTestingExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaHypothesisTestingKolmogorovSmirnovTestExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaIsotonicRegressionExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaKMeansExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaKernelDensityEstimationExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaLBFGSExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaLatentDirichletAllocationExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaLogisticRegressionWithLBFGSExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaMultiLabelClassificationMetricsExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaMulticlassClassificationMetricsExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaNaiveBayesExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaPCAExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaPowerIterationClusteringExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaPrefixSpanExample.java

In [ ]:
!pip install -q findspark

In [ ]:
import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["SPARK_HOME"] = "/content/spark-3.2.1-bin-hadoop2.7"

In [ ]:
import findspark
findspark.init()
from pyspark.sql import SparkSession

spark = SparkSession.builder.master("local[*]").getOrCreate()

In [ ]:
sc = spark.sparkContext
sc

In [ ]:
df = spark.read.csv('/content/u.data.csv',sep=";", inferSchema=True, header=True)

In [ ]:
df.show(5)

+-------+-------+------+---------+
|user_id|item_id|rating|timestamp|
+-------+-------+------+---------+
|    196|    242|     3|881250949|
|    186|    302|     3|891717742|
|     22|    377|     1|878887116|
|    244|     51|     2|880606923|
|    166|    346|     1|886397596|
+-------+-------+------+---------+
only showing top 5 rows

In [ ]:
df.groupby('rating').min('user_id').show()

+------+------------+
|rating|min(user_id)|
+------+------------+
|     1|           1|
|     3|           1|
|     5|           1|
|     4|           1|
|     2|           1|
+------+------------+

In [ ]:
df = df.select(["user_id","item_id","rating"])

In [ ]:
df.describe(['user_id']).show()

+-------+------------------+
|summary|           user_id|
+-------+------------------+
|  count|            100000|
|   mean|         462.48475|
| stddev|266.61442012750905|
|    min|                 1|
|    max|               943|
+-------+------------------+

# Средствами спарка вывести среднюю оценку для каждого фильма

In [ ]:
df.columns

['user_id', 'item_id', 'rating']

In [ ]:
df.groupby('item_id').avg('rating').show()

+-------+------------------+
|item_id|       avg(rating)|
+-------+------------------+
|    496| 4.121212121212121|
|    471|3.6108597285067874|
|    463| 3.859154929577465|
|    148|          3.203125|
|   1342|               2.5|
|    833| 3.204081632653061|
|   1088| 2.230769230769231|
|   1591|3.1666666666666665|
|   1238|             3.125|
|   1580|               1.0|
|   1645|               4.0|
|    392|3.5441176470588234|
|    623| 2.923076923076923|
|    540| 2.511627906976744|
|    858|               1.0|
|    737| 2.983050847457627|
|    243|2.4393939393939394|
|   1025|2.9318181818181817|
|   1084| 3.857142857142857|
|   1127| 2.909090909090909|
+-------+------------------+
only showing top 20 rows

# Посчитайте средствами спарка среднюю оценку для каждого жанра

In [ ]:
dfrat = rat_merged.drop(['movie_title', 'release_date'], axis=1)

dfrat

,user_id,movie_id,rating,unknown,Action,Adventure,Animation,Children,Comedy,Crime,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci_Fi,Thriller,War,Western
0,196,242,3,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,63,242,3,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,226,242,5,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,154,242,3,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,306,242,5,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,840,1674,4,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
99996,655,1640,3,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
99997,655,1637,3,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
99998,655,1630,3,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
99999,655,1641,3,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
df_sp = spark.createDataFrame(dfrat).collect()

In [ ]:
df_sp = dfrat

In [ ]:
import pyspark.pandas as ps

WARNING:root:'PYARROW_IGNORE_TIMEZONE' environment variable was not set. It is required to set this environment variable to '1' in both driver and executor sides if you use pyarrow>=2.0.0. pandas-on-Spark will set it for you but it does not work if there is a Spark context already launched.

In [ ]:
df_sp = ps.from_pandas(dfrat)

In [ ]:
df_sp.info()

<class 'pyspark.pandas.frame.DataFrame'>
Int64Index: 99991 entries, 0 to 99999
Data columns (total 22 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   user_id      99991 non-null  int64
 1   movie_id     99991 non-null  int64
 2   rating       99991 non-null  int64
 3   unknown      99991 non-null  int64
 4   Action       99991 non-null  int64
 5   Adventure    99991 non-null  int64
 6   Animation    99991 non-null  int64
 7   Children     99991 non-null  int64
 8   Comedy       99991 non-null  int64
 9   Crime        99991 non-null  int64
 10  Documentary  99991 non-null  int64
 11  Drama        99991 non-null  int64
 12  Fantasy      99991 non-null  int64
 13  Film-Noir    99991 non-null  int64
 14  Horror       99991 non-null  int64
 15  Musical      99991 non-null  int64
 16  Mystery      99991 non-null  int64
 17  Romance      99991 non-null  int64
 18  Sci_Fi       99991 non-null  int64
 19  Thriller     99991 non-null  int64
 20  War          99991 non-null  int64
 21  Western      99991 non-null  int64
dtypes: int64(22)

In [ ]:
x = (df_sp.where(df_sp['Action'] ==1))

In [ ]:
# from  pyspark library import 
# SparkSession
from pyspark.sql import SparkSession
  
# Building the SparkSession and name
# it :'pandas to spark'
spark = SparkSession.builder.appName(
  "pandas to spark").getOrCreate()
  
# Create the DataFrame with the help 
# of pd.DataFrame()
data = pd.DataFrame(dfrat)
  
# create DataFrame
df_spark = spark.createDataFrame(data)
  
df_spark.show(3)

+-------+--------+------+-------+------+---------+---------+--------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+
|user_id|movie_id|rating|unknown|Action|Adventure|Animation|Children|Comedy|Crime|Documentary|Drama|Fantasy|Film-Noir|Horror|Musical|Mystery|Romance|Sci_Fi|Thriller|War|Western|
+-------+--------+------+-------+------+---------+---------+--------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+
|    196|     242|     3|      0|     0|        0|        0|       0|     1|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|     63|     242|     3|      0|     0|        0|        0|       0|     1|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|    226|     242|     5|      0|     0|        0|        0|       0|     1|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
+-------+--------+------+-------+------+---------+---------+--------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+
only showing top 3 rows

In [ ]:
df_sp.columns

Index(['user_id', 'movie_id', 'rating', 'unknown', 'Action', 'Adventure',
       'Animation', 'Children', 'Comedy', 'Crime', 'Documentary', 'Drama',
       'Fantasy', 'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance',
       'Sci_Fi', 'Thriller', 'War', 'Western'],
      dtype='object')

In [ ]:
df_spark.groupby('unknown', 'Action', 'Adventure',
       'Animation', 'Children', 'Comedy', 'Crime', 'Documentary', 'Drama',
       'Fantasy', 'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance',
       'Sci_Fi', 'Thriller', 'War', 'Western').avg('rating').show(3)

+-------+------+---------+---------+--------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+------------------+
|unknown|Action|Adventure|Animation|Children|Comedy|Crime|Documentary|Drama|Fantasy|Film-Noir|Horror|Musical|Mystery|Romance|Sci_Fi|Thriller|War|Western|       avg(rating)|
+-------+------+---------+---------+--------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+------------------+
|      0|     1|        0|        0|       0|     0|    0|          0|    0|      0|        0|     0|      0|      1|      1|     0|       1|  0|      0|3.4237288135593222|
|      0|     0|        0|        0|       0|     0|    0|          0|    1|      0|        0|     0|      1|      0|      0|     0|       0|  1|      0|3.3508771929824563|
|      0|     1|        0|        0|       0|     0|    1|          0|    0|      0|        0|     0|      0|      1|      0|     0|       0|  0|      0|          3.359375|
+-------+------+---------+---------+--------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+------------------+
only showing top 3 rows

In [ ]:
 df_spark.groupby(['Action']).avg('rating').show()

+------+-----------------+
|Action|      avg(rating)|
+------+-----------------+
|     0|3.546934222198328|
|     1|3.480245417953027|
+------+-----------------+

In [ ]:
df_spark.groupby(['Action']).avg('rating').collect()[1]

Row(Action=1, avg(rating)=3.480245417953027)

In [ ]:
 z = ['unknown', 'Action', 'Adventure',
       'Animation', 'Children', 'Comedy', 'Crime', 'Documentary', 'Drama',
       'Fantasy', 'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance',
       'Sci_Fi', 'Thriller', 'War', 'Western']
 
 for i  in z:
   
   df_spark.groupby([i]).avg('rating').show()

+-------+------------------+
|unknown|       avg(rating)|
+-------+------------------+
|      0|3.5298929892989297|
|      1|               1.0|
+-------+------------------+

+------+-----------------+
|Action|      avg(rating)|
+------+-----------------+
|     0|3.546934222198328|
|     1|3.480245417953027|
+------+-----------------+

+---------+-----------------+
|Adventure|      avg(rating)|
+---------+-----------------+
|        0|3.534068508082284|
|        1|3.503526503308369|
+---------+-----------------+

+---------+------------------+
|Animation|       avg(rating)|
+---------+------------------+
|        0|3.5281161164484467|
|        1|3.5766990291262135|
+---------+------------------+

+--------+------------------+
|Children|       avg(rating)|
+--------+------------------+
|       0| 3.543535648482367|
|       1|3.3532442216652742|
+--------+------------------+

+------+------------------+
|Comedy|       avg(rating)|
+------+------------------+
|     0|3.5876081472084835|
|     1|3.3940734781442745|
+------+------------------+

+-----+------------------+
|Crime|       avg(rating)|
+-----+------------------+
|    0| 3.520894970414201|
|    1|3.6322780881440098|
+-----+------------------+

+-----------+------------------+
|Documentary|       avg(rating)|
+-----------+------------------+
|          0| 3.528775709693348|
|          1|3.6728232189973613|
+-----------+------------------+

+-----+------------------+
|Drama|       avg(rating)|
+-----+------------------+
|    0| 3.425302848775293|
|    1|3.6873793708484772|
+-----+------------------+

+-------+------------------+
|Fantasy|       avg(rating)|
+-------+------------------+
|      0|  3.53418019241882|
|      1|3.2152366863905324|
+-------+------------------+

+---------+------------------+
|Film-Noir|       avg(rating)|
+---------+------------------+
|        0|3.5229599625475787|
|        1|3.9215233698788228|
+---------+------------------+

+------+------------------+
|Horror|       avg(rating)|
+------+------------------+
|     0|3.5433170669877687|
|     1|3.2903893172841827|
+------+------------------+

+-------+------------------+
|Musical|       avg(rating)|
+-------+------------------+
|      0|3.5303092479771037|
|      1| 3.521396851029471|
+-------+------------------+

+-------+------------------+
|Mystery|       avg(rating)|
+-------+------------------+
|      0|3.5238743588119816|
|      1|  3.63813155386082|
+-------+------------------+

+-------+------------------+
|Romance|       avg(rating)|
+-------+------------------+
|      0|3.5076741586986215|
|      1| 3.621704948358255|
+-------+------------------+

+------+------------------+
|Sci_Fi|       avg(rating)|
+------+------------------+
|     0|  3.52536642944729|
|     1|3.5607227022780834|
+------+------------------+

+--------+------------------+
|Thriller|       avg(rating)|
+--------+------------------+
|       0|3.5357083424006963|
|       1|3.5090069495245064|
+--------+------------------+

+---+------------------+
|War|       avg(rating)|
+---+------------------+
|  0|3.5002042100383033|
|  1| 3.815811874866993|
+---+------------------+

+-------+------------------+
|Western|       avg(rating)|
+-------+------------------+
|      0|3.5282920814779337|
|      1|3.6132686084142396|
+-------+------------------+

In [ ]:
 z = ['unknown', 'Action', 'Adventure',
       'Animation', 'Children', 'Comedy', 'Crime', 'Documentary', 'Drama',
       'Fantasy', 'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance',
       'Sci_Fi', 'Thriller', 'War', 'Western']
df_av = [] 
 for i  in z:
   
   df_av += (df_spark.groupby([i]).avg('rating').collect()[1])

In [ ]:
av = df_av[1::2]
av

[1.0,
 3.480245417953027,
 3.503526503308369,
 3.5766990291262135,
 3.3532442216652742,
 3.3940734781442745,
 3.6322780881440098,
 3.6728232189973613,
 3.6873793708484772,
 3.2152366863905324,
 3.9215233698788228,
 3.2903893172841827,
 3.521396851029471,
 3.63813155386082,
 3.621704948358255,
 3.5607227022780834,
 3.5090069495245064,
 3.815811874866993,
 3.6132686084142396]

In [ ]:
av = list(zip(z, av))
av = sorted(av, key=lambda x: (x[1]), reverse = True)
av

[('Film-Noir', 3.9215233698788228),
 ('War', 3.815811874866993),
 ('Drama', 3.6873793708484772),
 ('Documentary', 3.6728232189973613),
 ('Mystery', 3.63813155386082),
 ('Crime', 3.6322780881440098),
 ('Romance', 3.621704948358255),
 ('Western', 3.6132686084142396),
 ('Animation', 3.5766990291262135),
 ('Sci_Fi', 3.5607227022780834),
 ('Musical', 3.521396851029471),
 ('Thriller', 3.5090069495245064),
 ('Adventure', 3.503526503308369),
 ('Action', 3.480245417953027),
 ('Comedy', 3.3940734781442745),
 ('Children', 3.3532442216652742),
 ('Horror', 3.2903893172841827),
 ('Fantasy', 3.2152366863905324),
 ('unknown', 1.0)]

In [ ]:
print(('жанр', 'средняя оценка'), *[(i[0], round(i[1],2)) for i in av], sep = '\n')

('жанр', 'средняя оценка')
('Film-Noir', 3.92)
('War', 3.82)
('Drama', 3.69)
('Documentary', 3.67)
('Mystery', 3.64)
('Crime', 3.63)
('Romance', 3.62)
('Western', 3.61)
('Animation', 3.58)
('Sci_Fi', 3.56)
('Musical', 3.52)
('Thriller', 3.51)
('Adventure', 3.5)
('Action', 3.48)
('Comedy', 3.39)
('Children', 3.35)
('Horror', 3.29)
('Fantasy', 3.22)
('unknown', 1.0)

# В спарке получить 2 датафрейма с 5-ю самыми популярными и самыми непопулярными фильмами (по количеству оценок, либо по самой оценке - на Ваш выбор)

In [ ]:
df_num = df_spark.groupBy('movie_id').sum('rating')
df_num.show()

+--------+-----------+
|movie_id|sum(rating)|
+--------+-----------+
|     474|        825|
|      29|        304|
|      26|        252|
|      65|        407|
|     191|       1149|
|    1224|         32|
|     558|        257|
|     222|       1336|
|     938|         72|
|     367|        588|
|     705|        547|
|     278|        194|
|      54|        337|
|    1217|        112|
|     277|        246|
|    1336|         18|
|    1042|         88|
|     385|        741|
|     564|         55|
|     241|        454|
+--------+-----------+
only showing top 20 rows

In [ ]:
df_num.sort("sum(rating)", ascending=False).show(5)

+--------+-----------+
|movie_id|sum(rating)|
+--------+-----------+
|      50|       2541|
|     100|       2111|
|     181|       2032|
|     258|       1936|
|     174|       1786|
+--------+-----------+
only showing top 5 rows

In [ ]:
df_num.sort('sum(rating)').show(5)

+--------+-----------+
|movie_id|sum(rating)|
+--------+-----------+
|    1671|          1|
|    1559|          1|
|     830|          1|
|    1329|          1|
|    1567|          1|
+--------+-----------+
only showing top 5 rows